#!/bin/bash

# Phase 2.4: Local Supabase Test Environment Setup
# This script sets up a local Supabase instance for testing using Supabase CLI
#
# Prerequisites:
#   - Docker or Podman must be installed and running
#   - Supabase CLI must be installed: npm install -g supabase
#
# Usage:
#   bash scripts/setup-test-db.sh
#
# After setup:
#   - Local Supabase runs at http://localhost:54321 (PostgREST API)
#   - PostgreSQL database at postgres://localhost:54322
#   - Supabase Studio at http://localhost:54323
#   - Test credentials are in .env.test

set -e

echo "=== Ceylon Haven Phase 2.4: Local Supabase Test Environment ==="
echo ""

# Check if Supabase CLI is available
if ! command -v supabase &> /dev/null; then
    echo "ERROR: Supabase CLI is not installed."
    echo "Install with: npm install -g supabase"
    exit 1
fi

# Check if Docker or Podman is available (required by Supabase CLI)
if ! command -v docker &> /dev/null && ! command -v podman &> /dev/null; then
    echo "ERROR: Docker or Podman is not installed."
    echo "Supabase CLI requires Docker/Podman to run local instances."
    echo "Install Docker: https://docs.docker.com/desktop/install/"
    exit 1
fi

echo "✓ Prerequisites found:"
echo "  - Supabase CLI: $(supabase --version)"
if command -v docker &> /dev/null; then
    echo "  - Docker: $(docker --version)"
else
    echo "  - Podman: $(podman --version)"
fi
echo ""

# Check if supabase/ directory exists (should exist after 'supabase init')
if [ ! -f supabase/config.toml ]; then
    echo "ERROR: supabase/config.toml not found."
    echo "Run 'supabase init' first to initialize the Supabase project."
    exit 1
fi

echo "Starting local Supabase instance..."
echo "This may take a minute on first run (downloading images, starting services)..."
echo ""

# Start Supabase
# The CLI will automatically:
# - Start PostgreSQL (at localhost:54322)
# - Start PostgREST API (at http://localhost:54321)
# - Start Auth service
# - Start Realtime service
# - Start Supabase Studio (at http://localhost:54323)
# - Apply migrations from db/migrations/
supabase start

echo ""
echo "✓ Supabase is running!"
echo ""

# Get credentials from supabase status
echo "Retrieving test credentials..."
STATUS_OUTPUT=$(supabase status)

# Parse the status output to extract credentials
ANON_KEY=$(echo "$STATUS_OUTPUT" | grep -i "anon key" | awk -F': ' '{print $2}' | tr -d ' ')
SERVICE_ROLE_KEY=$(echo "$STATUS_OUTPUT" | grep -i "service_role key" | awk -F': ' '{print $2}' | tr -d ' ')

if [ -z "$ANON_KEY" ] || [ -z "$SERVICE_ROLE_KEY" ]; then
    echo "ERROR: Could not extract credentials from supabase status"
    echo ""
    echo "Run this manually to see credentials:"
    echo "  supabase status"
    exit 1
fi

echo "✓ Credentials retrieved"
echo ""

# Create .env.test file with test configuration
echo "Creating .env.test file..."
cat > .env.test << EOF
# Phase 2.4 Local Supabase Test Configuration
# Auto-generated by scripts/setup-test-db.sh

# CRITICAL: These tests are LOCAL-ONLY
# DO NOT use these values in production
NODE_ENV=test

# Supabase PostgREST HTTP API (not raw PostgreSQL)
# Tests communicate through this HTTP API layer, matching production behavior
TEST_SUPABASE_URL=http://localhost:54321

# Test credentials (obtained from: supabase status)
TEST_SUPABASE_ANON_KEY=${ANON_KEY}
TEST_SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
EOF

echo "✓ Created .env.test"
echo ""

# Display configuration
echo "=== Local Supabase Configuration ==="
echo "PostgREST API URL: http://localhost:54321"
echo "PostgreSQL Database: postgresql://postgres:postgres@localhost:54322/postgres"
echo "Supabase Studio: http://localhost:54323"
echo ""
echo "Migrations applied: $(ls db/migrations/*.sql 2>/dev/null | wc -l) files"
echo ""

# Display next steps
echo "=== Next Steps ==="
echo ""
echo "1. Load test environment:"
echo "   source .env.test"
echo ""
echo "2. Run database integration tests:"
echo "   npm run test:integration:db"
echo ""
echo "3. View Supabase Studio (optional):"
echo "   Open http://localhost:54323 in your browser"
echo ""
echo "4. To stop Supabase:"
echo "   supabase stop"
echo ""
echo "5. To reset the database:"
echo "   supabase db reset"
echo ""
echo "=== Environment Variables ==="
cat .env.test
echo ""
echo "✓ Setup complete!"
